[[social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/BartekR"

  [social.params]
    icon = "brand-github"

[[social]]
  identifier = "twitter"
  name = "Twitter"
  url = "https://x.com/b_ratajczyk"

  [social.params]
    icon = "brand-twitter"