baseURL = "https://blog.bartekr.net/"
languageCode = "en-gb"
title = "BartekR"
theme = "hugo-theme-stack"
DefaultContentLanguage = "en"

[pagination]
  pagerSize = 10

[permalinks]
  post = ":year/:month/:day/:title"

[outputs]
  home = ["html", "json", "rss"]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[params]
  mainSections = ["post"]
  featuredImageField = "image"
  rssFullContent = true
  favicon = "/favicon.ico"

  [params.footer]
    since = 2017
    customText = "(c) Bartosz Ratajczyk"

  [params.dateFormat]
    published = "Jan 02, 2006"
    lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
    compact = true
    subtitle = "Azure. PowerShell. SQL. DevOps.<br />1 wife. 1 kid. 4 dogs. 5 cats."

    [params.sidebar.avatar]
      enabled = true
      local = true
      src = "/img/Bartek_SqlSatOslo2019_100x100.png"

  [params.article]
    headingAnchor = false
    math = false
    toc = true
    readingTime = true

  [params.comments]
    enabled = true
    provider = "utterances"

    [params.comments.utterances]
      repo = "BartekR/bartekr.github.io"
      issueTerm = "url"
      label = "blog-comment"

  [params.widgets]
    homepage = [
      { type = "search" },
      { type = "archives", params = { limit = 5 } },
      { type = "categories", params = { limit = 20 } },
      { type = "tag-cloud", params = { limit = 20 } }
    ]
    page = [
      { type = "toc" }
    ]

  [[params.social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/b_ratajczyk"
    params = { icon = "brand-twitter" }

  [[params.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/BartekR"
    params = { icon = "brand-github" }

  [[params.social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/bartoszratajczyk"
    params = { icon = "brand-linkedin" }

  [[params.social]]
    identifier = "mastodon"
    name = "Mastodon"
    url = "https://dataplatform.social/@b_ratajczyk"
    params = { icon = "brand-mastodon" }

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    identifier = "blogpl"
    name = "Old blog [PL]"
    url = "https://brinf.wordpress.com"
    weight = 3

  [[menu.main]]
    identifier = "series"
    name = "Series"
    url = "/series"
    weight = 4

  [[menu.main]]
    identifier = "containers-land"
    name = "Containers Land"
    url = "/containers-land"
    weight = 5

  [[menu.main]]
    identifier = "books"
    name = "Books"
    url = "/books"
    weight = 6

  [[menu.main]]
    identifier = "speaking"
    name = "Speaking"
    url = "/speaking"
    weight = 7

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 8

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 9

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search"
    weight = 10

[markup.highlight]
  noClasses = false

[services]
  [services.googleAnalytics]
    id = 'G-F8HV67CGLR'