baseURL = "https://blog.bartekr.net/"
languageCode = "en-gb"
title = "BartekR"
theme = "hugo-future-imperfect-slim"
DefaultContentLanguage = "en"
paginate = 10
googleAnalytics         = "UA-109318393-1"

[permalinks]
  post = ":year/:month/:day/:title"

[outputs]
  home                  = ["html", "json", "rss"]

[params]

  cssFiles              = ["default"]
  jsFiles               = ["default"]

  # Sets where "View More Posts" links to
  viewMorePostsLink     = "/post/"

  highlightjs           = true
  highlightjsTheme      = "vs2015"
  highlightjsLang       = ["powershell", "csharp"]
  
  [params.meta]
    description         = "BartekR blog. Previously known as String or binary data would be truncated"
    author              = "BartekR"
    favicon             = false
    svg                 = true

  [params.header]
    # Sets the navbarTitle that appears in the top left of the navigation bar
    navbarTitle         = "BartekR blog"
    # Sets navbarTitle to match the section of the website
    dynamicTitles       = false
    searchMenu          = true
    shareMenu           = false
    languageMenu        = true

  [params.intro]
    header                = "BartekR"
    paragraph             = "SQL Server. SSIS. PowerShell. Azure.<br/>1 wife. 1 kid. 4 dogs. 10 cats."
    rssIntro              = true
    socialIntro           = true
    # You may not want to display a long intro above content in the
    # single column layout used on smaller screens.
    hideWhenSingleColumn  = true
    # But you may want to always display the intro on the homepage.
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "/img/main/Bartek_SqlSatOslo2019_100x100.png"
      # Masks image in a certain shape. Supported are circle, triangle, diamond, and hexagon.
      shape               = "circle"
      width               = "100"
      alt                 = "BartekR profile pic"

  [params.sidebar]
    about               = "Posts about SQL Server, SSIS and automation for my future self, but you might find something useful."
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = false
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 1

  [[menu.main]]
    name              = "Blog [PL]"
    identifier        = "blogpl"
    url               = "https://brinf.wordpress.com"
    pre               = "<i class='fab fa-wordpress'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Series"
    identifier        = "series"
    url               = "/series"
    pre               = "<i class='fas fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Books"
    identifier        = "books"
    url               = "/books"
    pre               = "<i class='fas fa-book-reader'></i>"
    weight            = 4

  [[menu.main]]
    name              = "Speaking"
    identifier        = "speaking"
    url               = "/speaking"
    pre               = "<i class='fas fa-microphone-alt'></i>"
    weight            = 5

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "/categories"
    pre               = "<i class='fas fa-object-group'></i>"
    weight            = 6

  [[menu.main]]
    name              = "Tags"
    identifier        = "tags"
    url               = "/tags"
    pre               = "<i class='fas fa-tag'></i>"
    weight            = 7

[social]
twitter = "b_ratajczyk"
github = "BartekR"
linkedin = "bartoszratajczyk"
mastodon = "dataplatform.social/@b_ratajczyk"